### PR TITLE
All tests and functions

### PR DESCRIPTION
**Pull request by bosticc**
add tests and all functions

### CODE REVIEW

**Comment by bosticc** [comment]
> 1. Can you remove get_user_and_dataset_name and get_photo_name from all cloud functions? (but import them from file_path_utils.py)?
> 2. You'd prefer to have a single PR vs 4 PRs? I think 4 PRs are better.

Yup, I can do 4, just thought earlier one would be quicker. I'm about to send in another PR on this branch, and when you approve it I can just update the code on the other branches and hopefully there will be no conflicts

**Comment by zkoogle** [comment]
> > 1. Can you remove get_user_and_dataset_name and get_photo_name from all cloud functions? (but import them from file_path_utils.py)?
> > 2. You'd prefer to have a single PR vs 4 PRs? I think 4 PRs are better.
> 
> Yup, I can do 4, just thought earlier one would be quicker. I just sent in another PR on this branch, and if you approve it I can just update the code on the other branches and hopefully there will be no conflicts

The change looks good (but please remove all other tests except file_path_utils_test.py) and creating a new PR sounds ok, too (but why not modify this PR?)

**Comment by bosticc** [comment]
> > > 1. Can you remove get_user_and_dataset_name and get_photo_name from all cloud functions? (but import them from file_path_utils.py)?
> > > 2. You'd prefer to have a single PR vs 4 PRs? I think 4 PRs are better.
> > 
> > 
> > Yup, I can do 4, just thought earlier one would be quicker. I just sent in another PR on this branch, and if you approve it I can just update the code on the other branches and hopefully there will be no conflicts
> 
> The change looks good (but please remove all other tests except file_path_utils_test.py) and creating a new PR sounds ok, too (but why not modify this PR?)

Hm ok, I don't see the ones outside of file_path_utils_test.py, but maybe I'm missing them? Could you point them out to me in the file you saw them in? 
And sorry, I thought you wanted me to finish this branch and then work on the other 4 PRs that I already have open?

**Comment by zkoogle** [comment]
> > > > 1. Can you remove get_user_and_dataset_name and get_photo_name from all cloud functions? (but import them from file_path_utils.py)?
> > > > 2. You'd prefer to have a single PR vs 4 PRs? I think 4 PRs are better.
> > > 
> > > 
> > > Yup, I can do 4, just thought earlier one would be quicker. I just sent in another PR on this branch, and if you approve it I can just update the code on the other branches and hopefully there will be no conflicts
> > 
> > 
> > The change looks good (but please remove all other tests except file_path_utils_test.py) and creating a new PR sounds ok, too (but why not modify this PR?)
> 
> Hm ok, I don't see the ones outside of file_path_utils_test.py, but maybe I'm missing them? Could you point them out to me in the file you saw them in?
> And sorry, I thought you wanted me to finish this branch and then work on the other 4 PRs that I already have open?

This is what I see:
https://screenshot.googleplex.com/EPqUPsuueWb.png
(From https://github.com/jdstriker731/MLplayground/pull/19/files, after collapsing all of the file views).

**Comment by bosticc** [comment]
> > > > > 1. Can you remove get_user_and_dataset_name and get_photo_name from all cloud functions? (but import them from file_path_utils.py)?
> > > > > 2. You'd prefer to have a single PR vs 4 PRs? I think 4 PRs are better.
> > > > 
> > > > 
> > > > Yup, I can do 4, just thought earlier one would be quicker. I just sent in another PR on this branch, and if you approve it I can just update the code on the other branches and hopefully there will be no conflicts
> > > 
> > > 
> > > The change looks good (but please remove all other tests except file_path_utils_test.py) and creating a new PR sounds ok, too (but why not modify this PR?)
> > 
> > 
> > Hm ok, I don't see the ones outside of file_path_utils_test.py, but maybe I'm missing them? Could you point them out to me in the file you saw them in?
> > And sorry, I thought you wanted me to finish this branch and then work on the other 4 PRs that I already have open?
> 
> This is what I see:
> https://screenshot.googleplex.com/EPqUPsuueWb.png
> (From https://github.com/jdstriker731/MLplayground/pull/19/files, after collapsing all of the file views).

Thanks for the location, just took it out

**Comment by zkoogle** [comment]
Great! If you can, can you actually move all this changes to:
https://github.com/jdstriker731/MLplayground/pull/11
Because that's the one you linked to your self-evaluation.

**Comment by bosticc** [comment]
> Great! If you can, can you actually move all this changes to:
> #11
> Because that's the one you linked to your self-evaluation.

Done!

**Pull request closed without merging**
