### PR TITLE
Visualizer Retrieval Servlets

### PR DESCRIPTION
**Pull request by jdstriker731**
I just sent this as a PR so that I can be able to work from it using my personal computer. I still have to make the changes.

### CODE REVIEW

**Comment by jdstriker731** [comment]
I didn't realize you approved this branch as well @Zu. I made the changes you requested on Alvin's branch. Would you still want to look at them before I merge?

**Comment by zkoogle** [comment]
LGTM! But can you first merge this PR with the base so that the PR only
contains the retrieval servlets?

**Comment by jdstriker731** [comment]
So do you mean you want me to delete the authenticationservlet.java file, and just include the two retrieval servlets? (I re-created AuthenticateServlet.java because it seemed it got deleted as a result of either Alvin or Myles previous PR merges)

**Comment by zkoogle** [comment]
That one is fine, but I also see DatastoreMetadataStore.java,
MetadataStore.java, etc.

**Comment by jdstriker731** [comment]
Ohh okay, I forgot when I pull from that branch with those files, the changes I made to the comments/column limit didn't get added to the master branch. I'll delete those specific changes and send a new PR just for that.

**Pull request merged**
